-- =============================================================
-- 每日打卡积分系统 - 数据库初始化
-- 去 Supabase SQL Editor 执行：https://supabase.com/dashboard/project/azktetpcsxizlonodmwk/sql/new
-- =============================================================

-- 1. 任务模板表（管理员增删改）
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  points INTEGER NOT NULL DEFAULT 10,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 用户角色/积分表
CREATE TABLE IF NOT EXISTS user_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT,
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  total_points INTEGER DEFAULT 0,
  streak_days INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 每日打卡记录
CREATE TABLE IF NOT EXISTS check_ins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_by UUID REFERENCES auth.users(id),
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, date)
);

-- 4. 每次打卡勾选的任务明细
CREATE TABLE IF NOT EXISTS check_in_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  check_in_id BIGINT REFERENCES check_ins(id) ON DELETE CASCADE,
  task_id BIGINT REFERENCES tasks(id) ON DELETE SET NULL,
  task_name TEXT NOT NULL,
  points INTEGER NOT NULL
);

-- add status column to check_in_tasks (run separately if table already exists)
ALTER TABLE check_in_tasks ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending' 
  CHECK (status IN ('pending', 'approved', 'rejected'));

-- 5a. 积分变动日志
CREATE TABLE IF NOT EXISTS points_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  points INTEGER NOT NULL,
  reason TEXT NOT NULL,
  check_in_id BIGINT REFERENCES check_ins(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===== 插入示例任务（不重复插入） =====
INSERT INTO tasks (name, points, is_active)
SELECT * FROM (VALUES
  ('打视频', 1, true),
  ('运动20分钟', 1, true),
  ('学习1h', 1, true),
  ('学习2h', 2, true),
  ('学习3h', 3, true),
  ('学习4h', 5, true),
  ('学习6h', 8, true)
) AS v(name, points, is_active)
WHERE NOT EXISTS (
  SELECT 1 FROM tasks WHERE tasks.name = v.name
);

-- ===== 公共辅助函数（避免 RLS 无限递归） =====
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
$$ LANGUAGE sql STABLE SECURITY DEFINER;

-- 5b. 补签卡记录表
CREATE TABLE IF NOT EXISTS makeup_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  target_date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, target_date)
);

-- ===== 基础授权 =====
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;

-- ===== RLS 安全策略 =====
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE check_ins ENABLE ROW LEVEL SECURITY;
ALTER TABLE check_in_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE points_log ENABLE ROW LEVEL SECURITY;

-- 任务模板：所有人都可读，仅管理员可写
CREATE POLICY "tasks_select_all" ON tasks FOR SELECT USING (true);
CREATE POLICY "tasks_insert_admin" ON tasks FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "tasks_update_admin" ON tasks FOR UPDATE USING (public.is_admin());
CREATE POLICY "tasks_delete_admin" ON tasks FOR DELETE USING (public.is_admin());

-- user_profiles：仅自己和管理员可读
CREATE POLICY "profiles_select" ON user_profiles FOR SELECT USING (
  auth.uid() = id OR public.is_admin()
);
CREATE POLICY "profiles_insert" ON user_profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- check_ins：自己可读，管理员可读所有
CREATE POLICY "checkins_select" ON check_ins FOR SELECT USING (
  auth.uid() = user_id OR public.is_admin()
);
CREATE POLICY "checkins_insert" ON check_ins FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "checkins_update_admin" ON check_ins FOR UPDATE USING (public.is_admin());
CREATE POLICY "checkins_update_own" ON check_ins FOR UPDATE USING (auth.uid() = user_id);

-- check_in_tasks
CREATE POLICY "checkintasks_select" ON check_in_tasks FOR SELECT USING (
  check_in_id IN (SELECT id FROM check_ins WHERE user_id = auth.uid())
  OR public.is_admin()
);
CREATE POLICY "checkintasks_insert" ON check_in_tasks FOR INSERT WITH CHECK (
  check_in_id IN (SELECT id FROM check_ins WHERE user_id = auth.uid())
);

-- points_log
CREATE POLICY "pointslog_select" ON points_log FOR SELECT USING (
  auth.uid() = user_id OR public.is_admin()
);
CREATE POLICY "pointslog_insert_admin" ON points_log FOR INSERT WITH CHECK (public.is_admin());

-- makeup_log
ALTER TABLE makeup_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "makeup_log_select" ON makeup_log FOR SELECT USING (
  auth.uid() = user_id OR public.is_admin()
);
CREATE POLICY "makeup_log_insert" ON makeup_log FOR INSERT WITH CHECK (
  auth.uid() = user_id
);

-- ===== 函数：计算连续天数（含补签） =====
CREATE OR REPLACE FUNCTION calculate_streak(p_user_id UUID)
RETURNS INTEGER AS $$
DECLARE
  streak INTEGER := 0;
  check_date DATE := CURRENT_DATE;
  found_row RECORD;
BEGIN
  LOOP
    -- 检查当天是否有已批准的 '学习2h' 打卡
    SELECT ci.id INTO found_row
    FROM check_ins ci
    JOIN check_in_tasks cit ON cit.check_in_id = ci.id
    JOIN tasks t ON t.id = cit.task_id
    WHERE ci.user_id = p_user_id
      AND ci.date = check_date
      AND ci.status = 'approved'
      AND t.name = '学习2h';
    
    IF FOUND THEN
      streak := streak + 1;
      check_date := check_date - 1;
    ELSE
      -- 检查是否用了补签卡
      SELECT 1 INTO found_row FROM makeup_log
      WHERE user_id = p_user_id AND target_date = check_date;
      IF FOUND THEN
        streak := streak + 1;
        check_date := check_date - 1;
      ELSE
        EXIT;
      END IF;
    END IF;
  END LOOP;
  
  RETURN streak;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ===== 函数：根据连续天数返回奖励分 =====
CREATE OR REPLACE FUNCTION get_streak_bonus(p_streak INTEGER)
RETURNS INTEGER AS $$
BEGIN
  IF p_streak >= 31 THEN RETURN 5;
  ELSIF p_streak >= 16 THEN RETURN 3;
  ELSIF p_streak >= 8 THEN RETURN 2;
  ELSIF p_streak >= 2 THEN RETURN 1;
  ELSE RETURN 0;
  END IF;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ===== 函数：审批通过时自动加积分（含连续打卡奖励，避免重复加） =====
CREATE OR REPLACE FUNCTION approve_check_in(
  p_check_in_id BIGINT,
  p_reviewer_id UUID,
  p_status TEXT
) RETURNS void AS $$
DECLARE
  v_user_id UUID;
  v_points INTEGER;
  v_streak INTEGER;
  v_bonus INTEGER;
  v_already INTEGER;
  v_diff INTEGER;
BEGIN
  -- 获取打卡记录
  SELECT ci.user_id INTO v_user_id
  FROM check_ins ci WHERE ci.id = p_check_in_id;
  
  -- 计算本次总积分
  SELECT COALESCE(SUM(cit.points), 0) INTO v_points
  FROM check_in_tasks cit WHERE cit.check_in_id = p_check_in_id;
  
  -- 更新审批状态
  UPDATE check_ins
  SET status = p_status, reviewed_by = p_reviewer_id, reviewed_at = NOW()
  WHERE id = p_check_in_id;
  
  -- 如果通过，加积分
  IF p_status = 'approved' AND v_points > 0 THEN
    -- 基础积分
    INSERT INTO points_log (user_id, points, reason, check_in_id)
    VALUES (v_user_id, v_points, '打卡审批通过', p_check_in_id);
    
    -- 计算连续天数
    v_streak := calculate_streak(v_user_id);
    v_bonus := get_streak_bonus(v_streak);
    
    -- 查今天已加了多少奖励分
    SELECT COALESCE(SUM(points), 0) INTO v_already
    FROM points_log
    WHERE user_id = v_user_id
      AND reason LIKE '连续打卡奖励%'
      AND created_at::date = CURRENT_DATE;
    
    -- 只补差额
    v_diff := v_bonus - v_already;
    
    IF v_diff > 0 THEN
      INSERT INTO points_log (user_id, points, reason)
      VALUES (v_user_id, v_diff, '连续打卡奖励(' || v_streak || '天)');
      v_points := v_points + v_diff;
    END IF;
    
    -- 更新用户总积分和连续天数
    UPDATE user_profiles
    SET total_points = total_points + v_points,
        streak_days = v_streak
    WHERE id = v_user_id;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ===== 新函数：按任务逐个审批（管理员只通过选中的任务） =====
CREATE OR REPLACE FUNCTION approve_check_in_tasks(
  p_check_in_id BIGINT,
  p_reviewer_id UUID,
  p_task_ids BIGINT[]  -- check_in_tasks 表中要通过的 ID 列表
) RETURNS void AS $$
DECLARE
  v_user_id UUID;
  v_points INTEGER;
  v_streak INTEGER;
  v_bonus INTEGER;
  v_already INTEGER;
  v_diff INTEGER;
BEGIN
  SELECT user_id INTO v_user_id FROM check_ins WHERE id = p_check_in_id;
  
  -- 标记选中的为通过
  UPDATE check_in_tasks SET status = 'approved'
  WHERE id = ANY(p_task_ids) AND check_in_id = p_check_in_id AND status = 'pending';
  
  -- 标记未选中的为驳回
  UPDATE check_in_tasks SET status = 'rejected'
  WHERE check_in_id = p_check_in_id AND status = 'pending'
    AND (p_task_ids IS NULL OR id != ALL(p_task_ids));
  
  -- 检查是否有任何任务被通过
  IF array_length(p_task_ids, 1) IS NULL OR array_length(p_task_ids, 1) = 0 THEN
    -- 没有选中的：check_in 标记为 rejected
    UPDATE check_ins SET status = 'rejected', reviewed_by = p_reviewer_id, reviewed_at = NOW()
    WHERE id = p_check_in_id;
    RETURN;
  END IF;
  
  -- 计算通过任务的总分
  SELECT COALESCE(SUM(points), 0) INTO v_points
  FROM check_in_tasks WHERE check_in_id = p_check_in_id AND status = 'approved';
  
  -- 将 check_in 也标记为 approved（部分通过也算通过）
  UPDATE check_ins
  SET status = 'approved', reviewed_by = p_reviewer_id, reviewed_at = NOW()
  WHERE id = p_check_in_id;
  
  IF v_points > 0 THEN
    INSERT INTO points_log (user_id, points, reason, check_in_id)
    VALUES (v_user_id, v_points, '打卡审批通过', p_check_in_id);
    
    v_streak := calculate_streak(v_user_id);
    v_bonus := get_streak_bonus(v_streak);
    
    SELECT COALESCE(SUM(points), 0) INTO v_already
    FROM points_log WHERE user_id = v_user_id
      AND reason LIKE '连续打卡奖励%' AND created_at::date = CURRENT_DATE;
    
    v_diff := v_bonus - v_already;
    IF v_diff > 0 THEN
      INSERT INTO points_log (user_id, points, reason)
      VALUES (v_user_id, v_diff, '连续打卡奖励(' || v_streak || '天)');
      v_points := v_points + v_diff;
    END IF;
    
    UPDATE user_profiles
    SET total_points = total_points + v_points, streak_days = v_streak
    WHERE id = v_user_id;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ===== 函数：使用补签卡（自动补差额奖励分） =====
CREATE OR REPLACE FUNCTION use_makeup_card(
  p_user_id UUID,
  p_target_date DATE
) RETURNS TEXT AS $$
DECLARE
  v_balance INTEGER;
  v_streak INTEGER;
  v_bonus INTEGER;
  v_already INTEGER;
  v_diff INTEGER;
BEGIN
  -- 检查积分余额
  SELECT total_points INTO v_balance FROM user_profiles WHERE id = p_user_id;
  IF v_balance < 10 THEN
    RETURN '积分不足，需要10积分';
  END IF;
  
  -- 检查这天是否已经打过卡
  IF EXISTS (SELECT 1 FROM check_ins WHERE user_id = p_user_id AND date = p_target_date) THEN
    RETURN '该日已有打卡记录';
  END IF;
  
  -- 检查是否已补签过
  IF EXISTS (SELECT 1 FROM makeup_log WHERE user_id = p_user_id AND target_date = p_target_date) THEN
    RETURN '该日已补签过';
  END IF;
  
  -- 扣分
  UPDATE user_profiles SET total_points = total_points - 10 WHERE id = p_user_id;
  
  -- 记日志
  INSERT INTO points_log (user_id, points, reason)
  VALUES (p_user_id, -10, '使用补签卡(' || p_target_date || ')');
  
  -- 标记补签
  INSERT INTO makeup_log (user_id, target_date) VALUES (p_user_id, p_target_date);
  
  -- 重新计算连续天数
  v_streak := calculate_streak(p_user_id);
  v_bonus := get_streak_bonus(v_streak);
  
  -- 查今天已经加了多少奖励分
  SELECT COALESCE(SUM(points), 0) INTO v_already
  FROM points_log
  WHERE user_id = p_user_id
    AND reason LIKE '连续打卡奖励%'
    AND created_at::date = CURRENT_DATE;
  
  -- 只补差额
  v_diff := v_bonus - v_already;
  
  IF v_diff > 0 THEN
    UPDATE user_profiles SET 
      streak_days = v_streak,
      total_points = total_points + v_diff
    WHERE id = p_user_id;
    INSERT INTO points_log (user_id, points, reason)
    VALUES (p_user_id, v_diff, '连续打卡奖励(' || v_streak || '天)');
  ELSE
    UPDATE user_profiles SET streak_days = v_streak WHERE id = p_user_id;
  END IF;
  
  RETURN 'ok';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 函数：管理员手动加分
CREATE OR REPLACE FUNCTION admin_add_points(
  p_user_id UUID,
  p_points INTEGER,
  p_reason TEXT
) RETURNS void AS $$
BEGIN
  INSERT INTO points_log (user_id, points, reason)
  VALUES (p_user_id, p_points, p_reason);
  
  UPDATE user_profiles
  SET total_points = total_points + p_points
  WHERE id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ===== 触发器：注册时自动创建用户资料 =====
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.user_profiles (id, display_name, role)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'display_name', NEW.email), 'user');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 删除已有触发器再创建
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();
